---
title: "Report FeederwatchApp"
output: 
  html_document:
    theme:
      bootswatch: 'lux'
params:
  species_code: 'norcar'
  provinces: !r c('CA-QC', 'CA-ON')
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(zoo)
library(dplyr)
library(ggplot2)
library(tidyr)
library(plotly)
library(here)


all_data <- read.csv(here("data","data.csv"))

rare_sps <- all_data |> 
  dplyr::group_by(species_code) |> 
  dplyr::summarize(n = dplyr::n()) |> 
  dplyr::arrange(n) |> 
  dplyr::filter(n < 3)

freq_sps <- all_data |> 
  dplyr::group_by(species_code) |> 
  dplyr::summarize(n = dplyr::n()) |> 
  dplyr::arrange(n) |> 
  dplyr::filter(n > 3)

data <- dplyr::filter(all_data, species_code %in% freq_sps$species_code)
rare_data <- dplyr::filter(all_data, species_code %in% freq_sps$species_code)


```


```{r}
# The `params` object is available in the document.
print(params$provinces)
data_acc_sps_prov <- data |> 
  dplyr::filter(species_code == params$species_code,
                subnational1_code %in% params$provinces) |> # User input
  dplyr::mutate(yearmon = as.yearmon(as.Date(date))) |> 
  dplyr::group_by(yearmon, subnational1_code) |> 
  dplyr::summarize(n = dplyr::n()) |> 
  ungroup() |> 
  group_by(subnational1_code) |> 
  dplyr::mutate(cumsum = cumsum(n))



## LINEPLOT
    plotly::ggplotly(
      data_acc_sps_prov  |>
      ggplot2::ggplot(aes(x = as.Date(yearmon),
                          y = cumsum,
                          color = subnational1_code)) +
      ggplot2::geom_line(size = 0.5,
                         alpha = 0.5) +
      ggplot2::geom_point(alpha = 0.5) +
      ggplot2::scale_x_date(date_breaks = "1 month",
                            date_labels =  "%b %Y") +
      #   ggplot2::scale_color_brewer(palette = "Set2") +
      ggplot2::labs(title = paste('Period', min(data$date),
                                  "to",
                                  max(data$date)),
                    x = 'date',
                    y = 'observations')
  )

params$provinces
```

```{r}
## BOXPLOT
 data |> 
  dplyr::filter(species_code == params$species_code,
                subnational1_code %in% params$provinces) |> # User input
  dplyr::mutate(yearmon = as.yearmon(as.Date(date))) |> 
  mutate(month = factor(format(yearmon, "%b"),
                        levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun",
                                   "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))) |> 
  tidyr::pivot_longer(starts_with("fed_in"),
               values_to = 'fed_in_val' ,
               names_to= 'fed_in_names' ) |> 
  ggplot(aes(month, how_many)) +
  geom_boxplot()+
  geom_jitter(aes(color = subnational1_code))

params$provinces

```

